In [1]:
from astropy.table import Table
import pandas as pd

cat = Table.read('FujiBGSPhysProp_v1.1.fits', format='fits')

names = [name for name in cat.colnames if len(cat[name].shape) <= 1]
df  = cat[names].to_pandas()
df  = df.loc[:, ('RA', 'DEC', 'Z')]
df

WARNING: UnitsWarning: 'log(solMass)' did not parse as fits unit: 'log' is not a recognized function If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'log(solMass/yr)' did not parse as fits unit: 'log' is not a recognized function If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy^-2' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]

                RA        DEC         Z
0        59.188585 -31.414421  0.197085
1        59.216532 -31.429948  0.238940
2        59.229298 -31.399252  0.438447
3        59.237567 -31.465361  0.238333
4        59.264558 -31.423099  0.393163
...            ...        ...       ...
426262  240.452580  14.455760  0.649147
426263  240.574017  14.399732  0.509839
426264  241.081525  14.918211  0.319930
426265  241.106337  14.969940  0.615253
426266  241.206407  14.899658  0.075439

[426267 rows x 3 columns]

In [2]:
from my_functions import cutting, massage
import numpy as np

my_dict={'LOGM': [6,9], 'LOGSFR': [-10,0]}
my_data='FujiBGSPhysProp_v1.1'

class TableReader(object):
    def __init__(self, table, nObj=None, name=None):
        self.table = table

        if name is None:
            self.name='this_data'
        else:
            self.name=name

        self.read_table(nObj=nObj)
        

    def read_table(self, nObj=None):
        print("- load full table")
        data = self.table
        self.nObj = len(data)
        #
        # sky coordinates and redshift
        
        self.RA = np.array(data['RA']) # [deg]
        self.DEC = np.array(data['DEC'])   # [deg]
        self.Z = np.array(data['Z'])

my_thing=TableReader(cutting(my_data, my_dict))
print(my_thing.name)

# in running item=massage(cutting(my_data, my_dict), 'this_test') and print(item.RA), they would be the same array as reader

- load full table
this_data